# Generated by Django 5.0.3 on 2024-05-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_update', 'Order Update'), ('Promotion', 'Promotion'), ('event', 'Event')], default='order_update', max_length=20),
            preserve_default=False,
        ),
    ]
