# Generated by Django 5.0.3 on 2024-05-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100, unique=True)),
                ('meta_title', models.CharField(max_length=70)),
                ('meta_description', models.CharField(max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('meta_robots', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
