# Generated by Django 5.0.3 on 2024-04-22 21:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Bank Transfer'), ('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('stripe', 'Stripe')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
